### ISSUE TITLE
Some refactoring has to happen in order to continue supporting newer node.js versions

### ISSUE THREAD

**Issue by c4milo** [c4milo/node-inotify#46]
For more information, please refer to: 
https://groups.google.com/forum/#!topic/v8-users/6kSAbnUb-rQ

**Comment by cxreg** [comment]
Any chance of getting this module updated?  I'd like to use it with io.js

**Comment by c4milo** [comment]
I'm swamped these days and I haven't had the time to update it. I'm sorry :/

**Comment by c4milo** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by c4milo** [comment]
Support for Node 0.12.x landed in version 1.3.0. This should be fixed. Please re-open if you have any issues. @cxreg, Unfortunately io.js is not yet support due to issues with node-gyp, the build tool. https://github.com/TooTallNate/node-gyp/pull/564
