### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by poonamchawla** [c4milo/node-inotify#56]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'inotify' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\dashboardNodejs\package.json
5 verbose installManyTop reading scoped package data from C:\dashboardNodejs\node_modules\express\package.json
6 verbose installManyTop reading scoped package data from C:\dashboardNodejs\node_modules\pg\package.json
7 verbose readDependencies loading dependencies from C:\dashboardNodejs\package.json
8 silly cache add args [ 'inotify', null ]
9 verbose cache add spec inotify
10 silly cache add parsed spec { raw: 'inotify',
10 silly cache add   scope: null,
10 silly cache add   name: 'inotify',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed inotify@*
12 verbose addNamed "*" is a valid semver range for inotify
13 silly addNameRange { name: 'inotify', range: '*', hasData: false }
14 silly mapToRegistry name inotify
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/inotify
18 verbose addNameRange registry:https://registry.npmjs.org/inotify not in flight; fetching
19 verbose request uri https://registry.npmjs.org/inotify
20 verbose request no auth needed
21 info attempt registry request try #1 at 10:41:10 AM
22 verbose request id 30e7369976ea9ac4
23 verbose etag "4ZY5A5WQTFKRIA2LNLBYWNNEV"
24 http request GET https://registry.npmjs.org/inotify
25 http 304 https://registry.npmjs.org/inotify
26 silly get cb [ 304,
26 silly get   { date: 'Tue, 18 Aug 2015 14:41:10 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'cache-control': 'max-age=60',
26 silly get     etag: '"4ZY5A5WQTFKRIA2LNLBYWNNEV"',
26 silly get     age: '0',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-iad2140-IAD',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1439908870.432567,VS0,VE84',
26 silly get     vary: 'Accept' } ]
27 verbose etag https://registry.npmjs.org/inotify from cache
28 verbose get saving inotify to C:\Users\pchawla\AppData\Roaming\npm-cache\registry.npmjs.org\inotify\.cache.json
29 silly addNameRange number 2 { name: 'inotify', range: '*', hasData: true }
30 silly addNameRange versions [ 'inotify',
30 silly addNameRange   [ '0.1.2',
30 silly addNameRange     '0.1.3',
30 silly addNameRange     '0.1.4',
30 silly addNameRange     '0.1.5',
30 silly addNameRange     '0.1.6',
30 silly addNameRange     '0.1.7',
30 silly addNameRange     '0.1.8',
30 silly addNameRange     '0.2.0',
30 silly addNameRange     '0.2.1',
30 silly addNameRange     '0.2.2',
30 silly addNameRange     '1.0.0',
30 silly addNameRange     '1.1.0',
30 silly addNameRange     '1.2.0',
30 silly addNameRange     '1.2.1',
30 silly addNameRange     '1.3.0',
30 silly addNameRange     '1.4.0' ] ]
31 silly addNamed inotify@1.4.0
32 verbose addNamed "1.4.0" is a plain semver version for inotify
33 silly cache afterAdd inotify@1.4.0
34 verbose afterAdd C:\Users\pchawla\AppData\Roaming\npm-cache\inotify\1.4.0\package\package.json not in flight; writing
35 verbose afterAdd C:\Users\pchawla\AppData\Roaming\npm-cache\inotify\1.4.0\package\package.json written
36 silly install resolved [ { name: 'inotify',
36 silly install resolved     version: '1.4.0',
36 silly install resolved     author: { name: 'Camilo Aguilar', email: 'camilo.aguilar@gmail.com' },
36 silly install resolved     email: 'camilo.aguilar@gmail.com',
36 silly install resolved     keywords:
36 silly install resolved      [ 'inotify',
36 silly install resolved        'watch',
36 silly install resolved        'monitor',
36 silly install resolved        'watch files',
36 silly install resolved        'watch directories' ],
36 silly install resolved     license: 'MIT',
36 silly install resolved     description: 'inotify bindings for v8 javascript engine',
36 silly install resolved     repository:
36 silly install resolved      { type: 'git',
36 silly install resolved        url: 'git+ssh://git@github.com/c4milo/node-inotify.git' },
36 silly install resolved     engines: { node: '>=0.8' },
36 silly install resolved     main: 'inotify',
36 silly install resolved     dependencies: { nan: '^2.0.5' },
36 silly install resolved     scripts:
36 silly install resolved      { test: 'node-gyp configure build',
36 silly install resolved        install: 'node-gyp rebuild' },
36 silly install resolved     gypfile: true,
36 silly install resolved     contributors:
36 silly install resolved      [ [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object] ],
36 silly install resolved     gitHead: '16e8944a62d1aa4315e9cbec377970f056aaab68',
36 silly install resolved     bugs: { url: 'https://github.com/c4milo/node-inotify/issues' },
36 silly install resolved     homepage: 'https://github.com/c4milo/node-inotify#readme',
36 silly install resolved     _id: 'inotify@1.4.0',
36 silly install resolved     _shasum: 'c4a425d2035905a8da03f37426ff717160acdfee',
36 silly install resolved     _from: 'inotify@*',
36 silly install resolved     _npmVersion: '2.12.1',
36 silly install resolved     _nodeVersion: '0.12.7',
36 silly install resolved     _npmUser: { name: 'c4milo', email: 'camilo.aguilar@gmail.com' },
36 silly install resolved     maintainers: [ [Object], [Object] ],
36 silly install resolved     dist:
36 silly install resolved      { shasum: 'c4a425d2035905a8da03f37426ff717160acdfee',
36 silly install resolved        tarball: 'http://registry.npmjs.org/inotify/-/inotify-1.4.0.tgz' },
36 silly install resolved     directories: {},
36 silly install resolved     _resolved: 'https://registry.npmjs.org/inotify/-/inotify-1.4.0.tgz',
36 silly install resolved     readme: 'ERROR: No README data found!' } ]
37 info install inotify@1.4.0 into C:\dashboardNodejs
38 info installOne inotify@1.4.0
39 verbose installOne of inotify to C:\dashboardNodejs not in flight; installing
40 verbose lock using C:\Users\pchawla\AppData\Roaming\npm-cache\_locks\inotify-42d1d58f48eaf03b.lock for C:\dashboardNodejs\node_modules\inotify
41 silly install write writing inotify 1.4.0 to C:\dashboardNodejs\node_modules\inotify
42 verbose unbuild node_modules\inotify
43 silly gentlyRm C:\dashboardNodejs\node_modules\inotify is being purged from base C:\dashboardNodejs
44 verbose gentlyRm don't care about contents; nuking C:\dashboardNodejs\node_modules\inotify
45 verbose tar unpack C:\Users\pchawla\AppData\Roaming\npm-cache\inotify\1.4.0\package.tgz
46 verbose tar unpacking to C:\dashboardNodejs\node_modules\inotify
47 silly gentlyRm C:\dashboardNodejs\node_modules\inotify is being purged
48 verbose gentlyRm don't care about contents; nuking C:\dashboardNodejs\node_modules\inotify
49 silly gunzTarPerm modes [ '777', '666' ]
50 silly gunzTarPerm extractEntry package.json
51 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
52 silly gunzTarPerm extractEntry .npmignore
53 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
54 silly gunzTarPerm extractEntry README.md
55 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
56 silly gunzTarPerm extractEntry LICENSE
57 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
58 silly gunzTarPerm extractEntry example.js
59 silly gunzTarPerm modified mode [ 'example.js', 420, 438 ]
60 silly gunzTarPerm extractEntry inotify.js
61 silly gunzTarPerm modified mode [ 'inotify.js', 420, 438 ]
62 silly gunzTarPerm extractEntry binding.gyp
63 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
64 silly gunzTarPerm extractEntry src/bindings.cc
65 silly gunzTarPerm modified mode [ 'src/bindings.cc', 420, 438 ]
66 silly gunzTarPerm extractEntry src/bindings.h
67 silly gunzTarPerm modified mode [ 'src/bindings.h', 420, 438 ]
68 silly gunzTarPerm extractEntry src/node_inotify.cc
69 silly gunzTarPerm modified mode [ 'src/node_inotify.cc', 420, 438 ]
70 silly gunzTarPerm extractEntry src/node_inotify.h
71 silly gunzTarPerm modified mode [ 'src/node_inotify.h', 420, 438 ]
72 silly gunzTarPerm extractEntry AUTHORS
73 silly gunzTarPerm modified mode [ 'AUTHORS', 420, 438 ]
74 silly gunzTarPerm extractEntry .travis.yml
75 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
76 silly gunzTarPerm extractEntry Vagrantfile
77 silly gunzTarPerm modified mode [ 'Vagrantfile', 420, 438 ]
78 verbose write writing to C:\dashboardNodejs\node_modules\inotify\package.json
79 info preinstall inotify@1.4.0
80 verbose readDependencies loading dependencies from C:\dashboardNodejs\node_modules\inotify\package.json
81 silly prepareForInstallMany adding nan@^2.0.5 from inotify dependencies
82 verbose readDependencies loading dependencies from C:\dashboardNodejs\node_modules\inotify\package.json
83 silly cache add args [ 'nan@^2.0.5', null ]
84 verbose cache add spec nan@^2.0.5
85 silly cache add parsed spec { raw: 'nan@^2.0.5',
85 silly cache add   scope: null,
85 silly cache add   name: 'nan',
85 silly cache add   rawSpec: '^2.0.5',
85 silly cache add   spec: '>=2.0.5 <3.0.0',
85 silly cache add   type: 'range' }
86 silly addNamed nan@>=2.0.5 <3.0.0
87 verbose addNamed ">=2.0.5 <3.0.0" is a valid semver range for nan
88 silly addNameRange { name: 'nan', range: '>=2.0.5 <3.0.0', hasData: false }
89 silly mapToRegistry name nan
90 silly mapToRegistry using default registry
91 silly mapToRegistry registry https://registry.npmjs.org/
92 silly mapToRegistry uri https://registry.npmjs.org/nan
93 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
94 verbose request uri https://registry.npmjs.org/nan
95 verbose request no auth needed
96 info attempt registry request try #1 at 10:41:10 AM
97 verbose etag "41PIK59ZUA3ADEJCQ281I0TDQ"
98 http request GET https://registry.npmjs.org/nan
99 http 304 https://registry.npmjs.org/nan
100 silly get cb [ 304,
100 silly get   { date: 'Tue, 18 Aug 2015 14:41:10 GMT',
100 silly get     via: '1.1 varnish',
100 silly get     'cache-control': 'max-age=60',
100 silly get     etag: '"41PIK59ZUA3ADEJCQ281I0TDQ"',
100 silly get     age: '17',
100 silly get     connection: 'keep-alive',
100 silly get     'x-served-by': 'cache-iad2122-IAD',
100 silly get     'x-cache': 'HIT',
100 silly get     'x-cache-hits': '1',
100 silly get     'x-timer': 'S1439908870.722748,VS0,VE1',
100 silly get     vary: 'Accept' } ]
101 verbose etag https://registry.npmjs.org/nan from cache
102 verbose get saving nan to C:\Users\pchawla\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
103 silly addNameRange number 2 { name: 'nan', range: '>=2.0.5 <3.0.0', hasData: true }
104 silly addNameRange versions [ 'nan',
104 silly addNameRange   [ '0.3.0-wip',
104 silly addNameRange     '0.3.0-wip2',
104 silly addNameRange     '0.3.0',
104 silly addNameRange     '0.3.1',
104 silly addNameRange     '0.3.2',
104 silly addNameRange     '0.4.0',
104 silly addNameRange     '0.4.1',
104 silly addNameRange     '0.4.2',
104 silly addNameRange     '0.4.3',
104 silly addNameRange     '0.4.4',
104 silly addNameRange     '0.5.0',
104 silly addNameRange     '0.5.1',
104 silly addNameRange     '0.5.2',
104 silly addNameRange     '0.6.0',
104 silly addNameRange     '0.7.0',
104 silly addNameRange     '0.7.1',
104 silly addNameRange     '0.8.0',
104 silly addNameRange     '1.0.0',
104 silly addNameRange     '1.1.0',
104 silly addNameRange     '1.1.1',
104 silly addNameRange     '1.1.2',
104 silly addNameRange     '1.2.0',
104 silly addNameRange     '1.3.0',
104 silly addNameRange     '1.4.0',
104 silly addNameRange     '1.4.1',
104 silly addNameRange     '1.5.0',
104 silly addNameRange     '1.4.2',
104 silly addNameRange     '1.4.3',
104 silly addNameRange     '1.5.1',
104 silly addNameRange     '1.5.2',
104 silly addNameRange     '1.6.0',
104 silly addNameRange     '1.5.3',
104 silly addNameRange     '1.6.1',
104 silly addNameRange     '1.6.2',
104 silly addNameRange     '1.7.0',
104 silly addNameRange     '1.8.0',
104 silly addNameRange     '1.8.1',
104 silly addNameRange     '1.8.2',
104 silly addNameRange     '1.8.3',
104 silly addNameRange     '1.8.4',
104 silly addNameRange     '1.9.0',
104 silly addNameRange     '2.0.0',
104 silly addNameRange     '2.0.1',
104 silly addNameRange     '2.0.2',
104 silly addNameRange     '2.0.3',
104 silly addNameRange     '2.0.4',
104 silly addNameRange     '2.0.5' ] ]
105 silly addNamed nan@2.0.5
106 verbose addNamed "2.0.5" is a plain semver version for nan
107 silly cache afterAdd nan@2.0.5
108 verbose afterAdd C:\Users\pchawla\AppData\Roaming\npm-cache\nan\2.0.5\package\package.json not in flight; writing
109 verbose afterAdd C:\Users\pchawla\AppData\Roaming\npm-cache\nan\2.0.5\package\package.json written
110 silly install resolved [ { name: 'nan',
110 silly install resolved     version: '2.0.5',
110 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
110 silly install resolved     main: 'include_dirs.js',
110 silly install resolved     repository: { type: 'git', url: 'git://github.com/nodejs/nan.git' },
110 silly install resolved     scripts:
110 silly install resolved      { test: 'tap --gc test/js/*-test.js',
110 silly install resolved        'rebuild-tests': 'pangyp rebuild --msvs_version=2013 --directory test',
110 silly install resolved        docs: 'doc/.build.sh' },
110 silly install resolved     contributors:
110 silly install resolved      [ [Object],
110 silly install resolved        [Object],
110 silly install resolved        [Object],
110 silly install resolved        [Object],
110 silly install resolved        [Object],
110 silly install resolved        [Object],
110 silly install resolved        [Object] ],
110 silly install resolved     devDependencies:
110 silly install resolved      { bindings: '~1.2.1',
110 silly install resolved        'node-gyp': '~2.0.2',
110 silly install resolved        pangyp: '~2.2.0',
110 silly install resolved        tap: '~0.7.1',
110 silly install resolved        xtend: '~4.0.0' },
110 silly install resolved     license: 'MIT',
110 silly install resolved     gitHead: 'd13a2e9ce762fd130877b53c71d35963fa2cf689',
110 silly install resolved     bugs: { url: 'https://github.com/nodejs/nan/issues' },
110 silly install resolved     homepage: 'https://github.com/nodejs/nan#readme',
110 silly install resolved     _id: 'nan@2.0.5',
110 silly install resolved     _shasum: '365888014be1fd178db0cbfa258edf7b0cb1c408',
110 silly install resolved     _from: 'nan@>=2.0.5 <3.0.0',
110 silly install resolved     _npmVersion: '2.13.3',
110 silly install resolved     _nodeVersion: '3.0.0',
110 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
110 silly install resolved     maintainers: [ [Object], [Object] ],
110 silly install resolved     dist:
110 silly install resolved      { shasum: '365888014be1fd178db0cbfa258edf7b0cb1c408',
110 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-2.0.5.tgz' },
110 silly install resolved     directories: {},
110 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-2.0.5.tgz',
110 silly install resolved     readme: 'ERROR: No README data found!' } ]
111 info install nan@2.0.5 into C:\dashboardNodejs\node_modules\inotify
112 info installOne nan@2.0.5
113 verbose installOne of nan to C:\dashboardNodejs\node_modules\inotify not in flight; installing
114 verbose lock using C:\Users\pchawla\AppData\Roaming\npm-cache\_locks\nan-a5b622939f760440.lock for C:\dashboardNodejs\node_modules\inotify\node_modules\nan
115 silly install write writing nan 2.0.5 to C:\dashboardNodejs\node_modules\inotify\node_modules\nan
116 verbose unbuild node_modules\inotify\node_modules\nan
117 silly gentlyRm C:\dashboardNodejs\node_modules\inotify\node_modules\nan is being purged from base C:\dashboardNodejs
118 verbose gentlyRm don't care about contents; nuking C:\dashboardNodejs\node_modules\inotify\node_modules\nan
119 verbose tar unpack C:\Users\pchawla\AppData\Roaming\npm-cache\nan\2.0.5\package.tgz
120 verbose tar unpacking to C:\dashboardNodejs\node_modules\inotify\node_modules\nan
121 silly gentlyRm C:\dashboardNodejs\node_modules\inotify\node_modules\nan is being purged
122 verbose gentlyRm don't care about contents; nuking C:\dashboardNodejs\node_modules\inotify\node_modules\nan
123 silly gunzTarPerm modes [ '777', '666' ]
124 silly gunzTarPerm extractEntry package.json
125 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
126 silly gunzTarPerm extractEntry README.md
127 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
128 silly gunzTarPerm extractEntry include_dirs.js
129 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 438 ]
130 silly gunzTarPerm extractEntry nan_converters.h
131 silly gunzTarPerm modified mode [ 'nan_converters.h', 436, 438 ]
132 silly gunzTarPerm extractEntry LICENSE.md
133 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
134 silly gunzTarPerm extractEntry .dntrc
135 silly gunzTarPerm modified mode [ '.dntrc', 436, 438 ]
136 silly gunzTarPerm extractEntry appveyor.yml
137 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 438 ]
138 silly gunzTarPerm extractEntry doc/new.md
139 silly gunzTarPerm modified mode [ 'doc/new.md', 436, 438 ]
140 silly gunzTarPerm extractEntry doc/.build.sh
141 silly gunzTarPerm modified mode [ 'doc/.build.sh', 509, 511 ]
142 silly gunzTarPerm extractEntry doc/buffers.md
143 silly gunzTarPerm modified mode [ 'doc/buffers.md', 436, 438 ]
144 silly gunzTarPerm extractEntry doc/callback.md
145 silly gunzTarPerm modified mode [ 'doc/callback.md', 436, 438 ]
146 silly gunzTarPerm extractEntry doc/converters.md
147 silly gunzTarPerm modified mode [ 'doc/converters.md', 436, 438 ]
148 silly gunzTarPerm extractEntry doc/errors.md
149 silly gunzTarPerm modified mode [ 'doc/errors.md', 436, 438 ]
150 silly gunzTarPerm extractEntry doc/maybe_types.md
151 silly gunzTarPerm modified mode [ 'doc/maybe_types.md', 436, 438 ]
152 silly gunzTarPerm extractEntry doc/methods.md
153 silly gunzTarPerm modified mode [ 'doc/methods.md', 436, 438 ]
154 silly gunzTarPerm extractEntry doc/asyncworker.md
155 silly gunzTarPerm modified mode [ 'doc/asyncworker.md', 436, 438 ]
156 silly gunzTarPerm extractEntry doc/node_misc.md
157 silly gunzTarPerm modified mode [ 'doc/node_misc.md', 436, 438 ]
158 silly gunzTarPerm extractEntry doc/persistent.md
159 silly gunzTarPerm modified mode [ 'doc/persistent.md', 436, 438 ]
160 silly gunzTarPerm extractEntry doc/scopes.md
161 silly gunzTarPerm modified mode [ 'doc/scopes.md', 436, 438 ]
162 silly gunzTarPerm extractEntry doc/script.md
163 silly gunzTarPerm modified mode [ 'doc/script.md', 436, 438 ]
164 silly gunzTarPerm extractEntry doc/string_bytes.md
165 silly gunzTarPerm modified mode [ 'doc/string_bytes.md', 436, 438 ]
166 silly gunzTarPerm extractEntry doc/v8_internals.md
167 silly gunzTarPerm modified mode [ 'doc/v8_internals.md', 436, 438 ]
168 silly gunzTarPerm extractEntry doc/v8_misc.md
169 silly gunzTarPerm modified mode [ 'doc/v8_misc.md', 436, 438 ]
170 silly gunzTarPerm extractEntry nan.h
171 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
172 silly gunzTarPerm extractEntry nan_callbacks.h
173 silly gunzTarPerm modified mode [ 'nan_callbacks.h', 436, 438 ]
174 silly gunzTarPerm extractEntry nan_callbacks_12_inl.h
175 silly gunzTarPerm modified mode [ 'nan_callbacks_12_inl.h', 436, 438 ]
176 silly gunzTarPerm extractEntry nan_callbacks_pre_12_inl.h
177 silly gunzTarPerm modified mode [ 'nan_callbacks_pre_12_inl.h', 436, 438 ]
178 silly gunzTarPerm extractEntry nan_converters_43_inl.h
179 silly gunzTarPerm modified mode [ 'nan_converters_43_inl.h', 436, 438 ]
180 silly gunzTarPerm extractEntry nan_converters_pre_43_inl.h
181 silly gunzTarPerm modified mode [ 'nan_converters_pre_43_inl.h', 436, 438 ]
182 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
183 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
184 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
185 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
186 silly gunzTarPerm extractEntry nan_maybe_43_inl.h
187 silly gunzTarPerm modified mode [ 'nan_maybe_43_inl.h', 436, 438 ]
188 silly gunzTarPerm extractEntry nan_maybe_pre_43_inl.h
189 silly gunzTarPerm modified mode [ 'nan_maybe_pre_43_inl.h', 436, 438 ]
190 silly gunzTarPerm extractEntry nan_new.h
191 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
192 silly gunzTarPerm extractEntry nan_object_wrap.h
193 silly gunzTarPerm modified mode [ 'nan_object_wrap.h', 436, 438 ]
194 silly gunzTarPerm extractEntry nan_persistent_12_inl.h
195 silly gunzTarPerm modified mode [ 'nan_persistent_12_inl.h', 436, 438 ]
196 silly gunzTarPerm extractEntry nan_persistent_pre_12_inl.h
197 silly gunzTarPerm modified mode [ 'nan_persistent_pre_12_inl.h', 436, 438 ]
198 silly gunzTarPerm extractEntry nan_string_bytes.h
199 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 438 ]
200 silly gunzTarPerm extractEntry nan_weak.h
201 silly gunzTarPerm modified mode [ 'nan_weak.h', 436, 438 ]
202 silly gunzTarPerm extractEntry CHANGELOG.md
203 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
204 silly gunzTarPerm extractEntry tools/package.json
205 silly gunzTarPerm modified mode [ 'tools/package.json', 436, 438 ]
206 silly gunzTarPerm extractEntry tools/README.md
207 silly gunzTarPerm modified mode [ 'tools/README.md', 436, 438 ]
208 silly gunzTarPerm extractEntry tools/1to2.js
209 silly gunzTarPerm modified mode [ 'tools/1to2.js', 509, 511 ]
210 verbose write writing to C:\dashboardNodejs\node_modules\inotify\node_modules\nan\package.json
211 info preinstall nan@2.0.5
212 verbose readDependencies loading dependencies from C:\dashboardNodejs\node_modules\inotify\node_modules\nan\package.json
213 verbose readDependencies loading dependencies from C:\dashboardNodejs\node_modules\inotify\node_modules\nan\package.json
214 silly install resolved []
215 verbose about to build C:\dashboardNodejs\node_modules\inotify\node_modules\nan
216 info build C:\dashboardNodejs\node_modules\inotify\node_modules\nan
217 info linkStuff nan@2.0.5
218 silly linkStuff nan@2.0.5 has C:\dashboardNodejs\node_modules\inotify\node_modules as its parent node_modules
219 verbose linkBins nan@2.0.5
220 verbose linkMans nan@2.0.5
221 verbose rebuildBundles nan@2.0.5
222 info install nan@2.0.5
223 info postinstall nan@2.0.5
224 verbose unlock done using C:\Users\pchawla\AppData\Roaming\npm-cache\_locks\nan-a5b622939f760440.lock for C:\dashboardNodejs\node_modules\inotify\node_modules\nan
225 verbose about to build C:\dashboardNodejs\node_modules\inotify
226 info build C:\dashboardNodejs\node_modules\inotify
227 info linkStuff inotify@1.4.0
228 silly linkStuff inotify@1.4.0 has C:\dashboardNodejs\node_modules as its parent node_modules
229 verbose linkBins inotify@1.4.0
230 verbose linkMans inotify@1.4.0
231 verbose rebuildBundles inotify@1.4.0
232 verbose rebuildBundles [ 'nan' ]
233 info install inotify@1.4.0
234 verbose unsafe-perm in lifecycle true
235 info inotify@1.4.0 Failed to exec install script
236 verbose unlock done using C:\Users\pchawla\AppData\Roaming\npm-cache\_locks\inotify-42d1d58f48eaf03b.lock for C:\dashboardNodejs\node_modules\inotify
237 verbose stack Error: inotify@1.4.0 install: `node-gyp rebuild`
237 verbose stack Exit status 1
237 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
237 verbose stack     at EventEmitter.emit (events.js:110:17)
237 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
237 verbose stack     at ChildProcess.emit (events.js:110:17)
237 verbose stack     at maybeClose (child_process.js:1015:16)
237 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
238 verbose pkgid inotify@1.4.0
239 verbose cwd C:\dashboardNodejs
240 error Windows_NT 6.1.7601
241 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "inotify"
242 error node v0.12.7
243 error npm  v2.11.3
244 error code ELIFECYCLE
245 error inotify@1.4.0 install: `node-gyp rebuild`
245 error Exit status 1
246 error Failed at the inotify@1.4.0 install script 'node-gyp rebuild'.
246 error This is most likely a problem with the inotify package,
246 error not with npm itself.
246 error Tell the author that this fails on your system:
246 error     node-gyp rebuild
246 error You can get their info via:
246 error     npm owner ls inotify
246 error There is likely additional logging output above.
247 verbose exit [ 1, true ]
248 verbose unbuild node_modules\inotify
249 info preuninstall inotify@1.4.0
250 info uninstall inotify@1.4.0
251 verbose unbuild rmStuff inotify@1.4.0 from C:\dashboardNodejs\node_modules
252 info postuninstall inotify@1.4.0
253 silly gentlyRm C:\dashboardNodejs\node_modules\inotify is being purged from base C:\dashboardNodejs
254 verbose gentlyRm don't care about contents; nuking C:\dashboardNodejs\node_modules\inotify
255 silly vacuum-fs purging C:\dashboardNodejs\node_modules\inotify
256 silly vacuum-fs quitting because other entries in C:\dashboardNodejs\node_modules

**Comment by c4milo** [comment]
inotify itself is a linux kernel feature. So, it doesn't work on Windows. You can try https://github.com/paulmillr/chokidar it seems to work consistently for most people.
