### ISSUE TITLE
Error installing current: {"os":"linux","arch":"x64"}

### ISSUE THREAD

**Issue by Arturor72** [c4milo/node-inotify#63]
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "babel-preset-env" "--save" "dev"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! inotify@1.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by c4milo** [comment]
there is not enough information here to really tell what happened.

**Comment by dmaksimovic** [comment]
Also have this problem, is this package only for Linux? I'm using MacOS and I'm also getting:

$ sudo npm i -g inotify
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darko/.npm/_logs/2018-01-12T10_34_21_318Z-debug.log

**Comment by c4milo** [comment]
Yes, it is only for linux.
