### ISSUE TITLE
No OSX (Darwin) support? 

### ISSUE THREAD

**Issue by gurrkin** [c4milo/node-inotify#66]
Tried to install another module, that clearly relies somewhere on inotify.

I get this error: 

pm ERR! Darwin 16.6.0
npm ERR! argv "/Users/alexgurr/.nvm/versions/node/v6.10.3/bin/node" "/Users/alexgurr/.nvm/versions/node/v6.10.3/bin/npm" "install" "--save" "dev" "@storybook/cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for inotify@1.4.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

Does iNotify not support OS X?

**Comment by c4milo** [comment]
inotify is a linux kernel API only.
