### ISSUE TITLE
Promise.resolve() does not work correctly inside an inotify callback

### ISSUE THREAD

**Issue by redneb** [c4milo/node-inotify#67]
`Promise.resolve()` returns an already resolved promise and therefore `Promise.resolve().then(...)` should execute the promise callback immediately. But when I try that from within an inotify callback, the promise callback never gets called. Here's a minimal example:

    const Inotify = require("inotify").Inotify;
    
    new Inotify().addWatch({
    	path: ".",
    	watch_for: Inotify.IN_ALL_EVENTS,
    	callback: ev => {
    		console.log("this is an inotify callback");
    		Promise.resolve().then(() => {
    			console.log("done");
    		});
    	},
    });

When I run this with node v8.4.0 and do a `touch .` in a different terminal, I do not see `done` in the output.

**Comment by c4milo** [comment]
@redneb I don't think we have added support for promises yet. Any help is appreciated.

**Comment by redneb** [comment]
This issue is not about promises per se, nor I'm asking you to add support for promises to `node-inotify`. I am just pointing out that while the following piece of code:

**Comment by redneb** [comment]
Here's another complete example that has the same problem and does not use promises at all:

    const Inotify = require("inotify").Inotify;
    
    new Inotify().addWatch({
    	path: ".",
    	watch_for: Inotify.IN_ALL_EVENTS,
    	callback: ev => {
    		console.log("hello");
    		process.nextTick(() => {
    			console.log("done");
    		});
    	},
    });

I expect that every time the above program prints `hello`, it would be (almost) immediately followed by another line of output, `done`. But it doesn't. It's as if the next tick never happens.

**Comment by c4milo** [comment]
@redneb thanks for the detailed issue report! I'm looking into it and I will keep you posted here.

**Comment by c4milo** [comment]
@redneb, alright, I think I know what I need to do to fix this. I will find some time tonight to do it.

**Comment by c4milo** [comment]
@redneb thanks again, the fixed landed on v1.4.2.
